# Notes:
# PecApprox & FitExp -  numerically unstable & system dependent, so check if scipy's least square function returns success
# GUI - no testing at all

before_script:
  - apt-get update
  - apt-get install -y python3-scipy
  - apt-get install -y python3-tk
  - apt-get install -y python3-matplotlib
  - apt-get install -y python3-pip

test:
  script:
    - pip3 install -e .
    - python3 test/unittests.py
    - python3 -m x1fd3 PecApprox input/init_emo.txt input/pw_pec.txt
    - cat PecApprox_1.log | grep "PEC fit done:"
    - python3 -m x1fd3 LevelsPW input/params_levels.txt input/pw_pec.txt
    - diff test/LevelsPW.ref LevelsPW_1.log
    - python3 -m x1fd3 LevelsAn input/params_levels.txt input/fitted_emo.txt
    - diff test/LevelsAn.ref LevelsAn_1.log
    - python3 -m x1fd3 SpectrumPW input/params_spectrum.txt input/pw_pec.txt input/pw_dm.txt
    - diff test/SpectrumPW.ref SpectrumPW_1.log
    - python3 -m x1fd3 SpectrumAn input/params_spectrum.txt input/fitted_emo.txt input/pw_dm.txt
    - diff test/SpectrumAn.ref SpectrumAn_1.log
    - python3 -m x1fd3 FitExp input/params_fit.txt input/fitted_emo.txt input/pw_pec.txt input/exp_levels.txt 
    - cat FitExp_1.log | grep "PEC fit done:"
