before_script:
  - apt-get update
  - apt-get install -y python3-scipy

test:
  script:
    - diff test/pw_pec_approx.ref <(python3 pw_pec_approx.py pw_pec.txt init_emo_params.txt)
    - diff test/level_calc_pw_pec.ref <(python3 level_calc_pw_pec.py vr_level_calc_params.txt pw_pec.txt)
    - diff test/level_calc_an_pec.ref <(python3 level_calc_an_pec.py vr_level_calc_params.txt fitted_emo_params.txt)
    - diff test/spectrum_calc_pw_pec.ref <(python3 spectrum_calc_pw_pec.py vr_spectrum_calc_params.txt pw_pec.txt pw_dm.txt)
    - diff test/spectrum_calc_an_pec.ref <(python3 spectrum_calc_an_pec.py vr_spectrum_calc_params.txt fitted_emo_params.txt pw_dm.txt)
# broken
#    - diff test/fit_pec_to_exp_levels.ref <(python3 fit_pec_to_exp_levels.py vr_fit_params.txt fitted_emo_params.txt pw_pec.txt exp_levels.txt)
