# Notes:
# FitExp - numerically unstable (by design) & system dependent, so check if scipy's least square function returns success
# GUI - not testing at all

before_script:
  - apt-get update
  - apt-get install -y python3-scipy
  - apt-get install -y python3-tk

test:
  script:
    - python3 -m x1fd3 PecApprox input/pw_pec.txt input/init_emo_params.txt
    - diff test/PecApprox.ref PecApprox_1.log
    - python3 -m x1fd3 LevelsPW input/vr_level_calc_params.txt input/pw_pec.txt
    - diff test/LevelsPW.ref LevelsPW_1.log
    - python3 -m x1fd3 LevelsAn input/vr_level_calc_params.txt input/fitted_emo_params.txt
    - diff test/LevelsAn.ref LevelsAn_1.log
    - python3 -m x1fd3 SpectrumPW input/vr_spectrum_calc_params.txt input/pw_pec.txt input/pw_dm.txt
    - diff test/SpectrumPW.ref SpectrumPW_1.log
    - python3 -m x1fd3 SpectrumAn input/vr_spectrum_calc_params.txt input/fitted_emo_params.txt input/pw_dm.txt
    - diff test/SpectrumAn.ref SpectrumAn_1.log
    - python3 -m x1fd3 FitExp input/vr_fit_params.txt input/fitted_emo_params.txt input/pw_pec.txt input/exp_levels.txt 
    - cat FitExp_1.log | grep "PEC fit done:"
