before_script:
  - apt-get update
  - apt-get install -y python3-scipy

test:
  script:
    - diff test/pw_pec_approx.ref <(python3 pw_pec_approx.py pw_pec.txt init_emo_params.txt)
    - diff test/level_calc_pw_pec.ref <(python level_calc_pw_pec.py vr_level_calc_params.txt pw_pec.txt)

